### ISSUE TITLE
训练配置文件

### ISSUE THREAD

**Issue by sorrowyn** [ZhenZHAO/lassl#1]
首先，感谢你公布自己的工作。
目前只有cifar10的配置文件，能否提供cifar100和SVHN和配置文件。
xiaomylei@163.com

**Comment by ZhenZHAO** [comment]
all of them hold the same resolution of 32*32..... I cannot find the details, but they should share the same hyper-parameters.

Just note that, when training SVHN, please remove the flip augmentations, simple because it will change the semantics.
